from typing import Dict, Any, Optional
from typing_extensions import TypedDict, Annotated
from langchain.prompts import ChatPromptTemplate

from app.domain.llm_providers.base import BaseLLMProvider


class GeneratedDraft(TypedDict):
    """Structured draft generated by the content generator."""

    draft: Annotated[str, ..., "The generated content draft matching the request"]


class ContentGeneratorAgent:
    def __init__(self, llm: BaseLLMProvider):
        self.llm = llm
        self.content_prompt = ChatPromptTemplate.from_messages(
            [
                (
                    "system",
                    """You are a professional content creator who generates high-quality, engaging content.
You have exceptional reading comprehension and ALWAYS follow the exact requirements in the user's content request.

When generating content:
- PRECISELY follow any word count limits mentioned in the original request
- Match the tone, style, and voice requested
- Create engaging content tailored to the target audience
- Ensure factual accuracy and strategic keyword placement

You are skilled at interpreting instructions directly from natural language requests and delivering exactly what was asked for.
If a user asks for "50 word content" or "keep it under 100 words" or any similar instruction, you will honor that request precisely.

Your goal is to deliver content that follows the user's specifications WITHOUT needing additional processing or tracking.
\n
Default behavior:
- Unless the request clearly and explicitly asks for MULTIPLE pieces with a specific number (e.g., "3 posts", "two tweets", "a 5-part series"), produce EXACTLY ONE piece of content.
- Do NOT invent multiple posts or sections like "Post 1", "Post 2" unless the request explicitly specifies a count.

Return your output as a structured JSON object.
""",
                ),
                (
                    "human",
                    """Theme: {theme}
Brand Tone: {brand_tone}
Target Audience: {target_audience}
Original Request: {user_qurey}
Additional Context: {additional_context}

Please generate content that precisely follows the requirements in the original request.""",
                ),
            ]
        )

    async def generate_content(
        self,
        theme: str,
        user_qurey: str = "",
        brand_tone: Optional[str] = None,
        target_audience: Optional[str] = None,
        additional_context: Optional[str] = None,
    ) -> Dict[str, Any]:
        """
        Generate draft content based on theme and the original content request.

        Args:
            theme: The content theme or topic
            user_qurey: Original user query containing any specific instructions
            brand_tone: Optional brand voice/tone to match
            target_audience: Optional target audience description
            additional_context: Optional additional context or requirements

        Returns:
            Dict containing the content draft
        """

        result = await self.llm.generate(
            prompt=self.content_prompt,
            input={
                "theme": theme,
                "brand_tone": brand_tone or "Professional and engaging",
                "target_audience": target_audience or "General audience",
                "user_qurey": user_qurey or "No specific requirements provided",
                "additional_context": additional_context or "",
            },
            output_schema=GeneratedDraft,
        )

        return {
            "draft": result["draft"],
            "metadata": {
                "theme": theme,
            },
        }
